apiVersion: batch/v1
kind: Job
metadata:
  name: 'doublewords-batch-${SELECTED_SEGMENT}'
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: doublewords-playground
        image: kelog/doublewords:v03
        resources:
          limits:
            memory: "500Mi"
            cpu: 1000m
        env:
        - name: JAVA_OPTS
          value: '-Xmx400m -Xms400m'
        - name: MODE
          value: WORKER
        - name: RESULTS_PUBLISHER
          value: HTTP
        - name: SINK_URL
          value: http://92.222.76.126:1234/store
        - name: SEGMENTS_COUNT
          value: '${SEGMENTS_COUNT}'
        - name: SELECTED_SEGMENT
          value: '${SELECTED_SEGMENT}'
