package pl.kelog.worker;

import java.util.HashSet;
import java.util.Set;

import static java.util.Arrays.asList;

/**
 * Some double words are just boring and "too obvious",
 * we filter them out here to save some time.
 */
class WordsFilter {
    
    private static final int MIN_WORD_LENGTH = 4;
    private static Set<String> BANNED_PREFIXES = new HashSet<>(asList(
            "ben",
            "bez",
            "beze",
            "blisko",
            "celem",
            "chyba",
            "co",
            "dla",
            "do",
            "dzięki",
            "dziela",
            "gwoli",
            "jako",
            "kole",
            "koło",
            "kontra",
            "krom",
            "króm",
            "ku",
            "lada",
            "miast",
            "miasto",
            "między",
            "mimo",
            "na",
            "nad",
            "nade",
            "naokoło",
            "naprzeciw",
            "naprzeciwko",
            "niby",
            "niczym",
            "nieopodal",
            "o",
            "obok",
            "od",
            "ode",
            "odnośnie",
            "około",
            "oprócz",
            "per",
            "po",
            "po",
            "pod",
            "podczas",
            "pode",
            "podle",
            "pomiędzy",
            "pomimo",
            "ponad",
            "poniżej",
            "poprzez",
            "pośród",
            "powyżej",
            "poza",
            "prócz",
            "prze",
            "przeciw",
            "przeciwko",
            "przed",
            "przed",
            "przede",
            "przez",
            "przeze",
            "przy",
            "skutkiem",
            "skyrs",
            "spod",
            "spode",
            "spomiędzy",
            "spośród",
            "spoza",
            "sprzed",
            "śród",
            "ustami",
            "w",
            "wbrew",
            "we",
            "wedle",
            "według",
            "wewnątrz",
            "wobec",
            "wokół",
            "wokoło",
            "wraz",
            "wskutek",
            "wśród",
            "wzdłuż",
            "względem",
            "z",
            "za",
            "zamiast",
            "ze",
            "zewnątrz",
            "zez",
            "znad",
            "znade",
            "zza",
            "anty",
            "auto",
            "arcy",
            "super",
            "mili",
            "mikro",
            "makro",
            "kilo",
            "techno",
            "pseudo",
            "mono",
            "mini",
            "jedno",
            "hiper",
            "homo",
            "prawo",
            "lewo",
            "prosto",
            "pseudo",
            "euro",
            "święto",
            "ciemn",
            "radio",
            "seks",
            "foto",
            "nitro",
            "nisko",
            "wysoko",
            "trzy"
    ));
    
    static boolean isSensibleWord(String word) {
        return word.length() >= MIN_WORD_LENGTH && BANNED_PREFIXES.stream().noneMatch(word::startsWith);
    }
}
